// Generated by CoffeeScript 2.7.0
(function() {
  // ============================================================
  //  BOUNCY BUNNY - LEARNING VERSION
  //  Fill in the code to make the game work!
  //  Look for "YOUR CODE HERE" sections
  // ============================================================

  // --- Canvas size (don't change these) ---
  var BUNNY_SIZE, BUNNY_X, CARROT_COINS, CARROT_POINTS, FLAP_POWER, GAP_SIZE, GRAVITY, H, POWERUP_EVERY, SKINS, SKIN_COST, SPAWN_TIME, W, WALL_SPEED, WALL_WIDTH, applyGravity, bestScore, boxesOverlap, btns, bunnySpeed, bunnyY, canvas, carrots, checkCarrotCollision, checkCeiling, checkGround, checkPowerupCollision, checkWallCollision, coins, ctx, currentSkin, draw, drawBackground, drawBtn, drawBunny, drawCarrots, drawGame, drawHome, drawOver, drawPowerupIndicators, drawPowerups, drawScore, drawShop, drawWalls, flap, frames, gameLoop, gameOver, handleClick, hasAxe, hasWacker, hitBtn, loadData, moveBunny, moveCarrots, movePowerups, moveWalls, onClick, onKey, onTouch, owned, powerups, removeOldStuff, resetGame, saveData, score, screen, setup, spawnWall, update, waiting, walls;

  W = 480;

  H = 640;

  // ============================================================
  // CHALLENGE 1: Set up the game constants!
  // ============================================================

  // Where does the bunny start? (left side of screen)
  BUNNY_X = 100;

  // How big is the bunny circle?
  // Try a number between 15 and 30
  BUNNY_SIZE = 20;

  // How fast does the bunny fall?
  // Try a number between 0.3 and 0.8
  // Bigger number = falls faster!
  GRAVITY = 0.5;

  // How strong is a flap/jump?
  // Try a number between 7 and 12
  // Bigger number = jumps higher!
  FLAP_POWER = 8;

  // How fast do walls move toward the bunny?
  // Try a number between 2 and 5
  WALL_SPEED = 4;

  // How wide are the walls?
  WALL_WIDTH = 60;

  // How big is the gap between top and bottom walls?
  // Try a number between 150 and 220
  // Smaller gap = harder game!
  GAP_SIZE = 165;

  // How often do new walls appear? (in frames)
  // 60 frames = about 1 second
  SPAWN_TIME = 100;

  // How often do powerups appear? (every N walls)
  POWERUP_EVERY = 15;

  // How many points for collecting a carrot?
  CARROT_POINTS = 10;

  // How many coins do you earn per carrot?
  CARROT_COINS = 5;

  // ============================================================
  // SKIN COLORS - Change these to any colors you like!
  // ============================================================
  SKINS = [
    {
      name: 'White',
      color: '#FFFFFF'
    },
    {
      name: 'Grey',
      color: '#AAAAAA'
    },
    {
      name: 'Gold',
      color: '#FFD700'
    },
    {
      name: 'Pink',
      color: '#FFB6C1'
    },
    {
      name: 'Blue',
      color: '#6699FF'
    },
    {
      name: 'Red',
      color: '#FF6666'
    }
  ];

  SKIN_COST = [0, 30, 50, 70, 100, 150];

  // ============================================================
  // GAME VARIABLES (don't change this section)
  // ============================================================
  canvas = null;

  ctx = null;

  screen = 'HOME';

  bunnyY = H / 2;

  bunnySpeed = 0;

  walls = [];

  carrots = [];

  powerups = [];

  score = 0;

  frames = 0;

  hasAxe = false;

  hasWacker = false;

  waiting = true;

  bestScore = 0;

  coins = 0;

  currentSkin = 0;

  owned = [true, false, false, false, false, false];

  btns = {};

  // ============================================================
  // SETUP (don't change this section)
  // ============================================================
  setup = function() {
    canvas = document.getElementById('gameCanvas');
    ctx = canvas.getContext('2d');
    loadData();
    canvas.addEventListener('click', onClick);
    canvas.addEventListener('touchstart', onTouch, {
      passive: false
    });
    document.addEventListener('keydown', onKey);
    return gameLoop();
  };

  // ============================================================
  // SAVE / LOAD (don't change this section)
  // ============================================================
  saveData = function() {
    localStorage.setItem('bb4_best', bestScore);
    localStorage.setItem('bb4_coins', coins);
    localStorage.setItem('bb4_skin', currentSkin);
    return localStorage.setItem('bb4_owned', JSON.stringify(owned));
  };

  loadData = function() {
    var savedOwned;
    bestScore = parseInt(localStorage.getItem('bb4_best') || '0');
    coins = parseInt(localStorage.getItem('bb4_coins') || '0');
    currentSkin = parseInt(localStorage.getItem('bb4_skin') || '0');
    savedOwned = localStorage.getItem('bb4_owned');
    return owned = savedOwned ? JSON.parse(savedOwned) : [true, false, false, false, false, false];
  };

  // ============================================================
  // CHALLENGE 2: Draw the bunny!
  // ============================================================
  // Draw a circle with eyes for our bunny character

  // You will need to:
  // - Set the fill color using SKINS[skinIndex].color
  // - Draw a circle using ctx.arc(x, y, radius, 0, Math.PI * 2)
  // - Add a black outline using ctx.stroke()
  // - Draw two small circles for eyes

  // HINTS:
  // - Use ctx.fillStyle to set colors
  // - Use ctx.beginPath() before drawing shapes
  // - Use ctx.fill() to fill shapes
  // - The eyes should be at x-6 and x+6, slightly above center (y-4)
  drawBunny = function(x, y, skinIndex = currentSkin) {
    // YOUR CODE HERE
    // Step 1: Set fill color to the skin color and draw the body circle  
    ctx.fillStyle = SKINS[skinIndex].color;
    ctx.beginPath();
    ctx.arc(x, y, BUNNY_SIZE, 0, Math.PI * 2);
    ctx.fill();
    // Step 2: Add a black outline (set strokeStyle, lineWidth, then stroke)
    ctx.strokeStyle = 'black';
    ctx.lineWidth = 5;
    ctx.stroke();
    // Step 3: Draw two small black circles for eyes (radius 3)
    //ctx.fillStyle = '#000000'
    //ctx.arc(x, y, 3, 0, Math.PI * 2)
    ctx.fillStyle = 'black';
    ctx.beginPath();
    ctx.arc(x - 6, y - 4, 5, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = 'black';
    ctx.beginPath();
    ctx.arc(x + 6, y - 4, 5, 0, Math.PI * 2);
    return ctx.fill();
  };

  // ============================================================
  // CHALLENGE 3: Draw the walls!
  // ============================================================
  // Draw brown rectangles for top walls and green for bottom walls

  // You will need to:
  // - Loop through each wall in the walls array
  // - Draw a brown rectangle from the top of screen down to wall.topH
  // - Draw a green rectangle from wall.botY down to the ground

  // HINTS:
  // - Brown color: '#8B4513'
  // - Green color: '#228B22'
  // - Use ctx.fillRect(x, y, width, height)
  // - Top wall starts at y=0
  // - Bottom wall height is: H - 30 - wall.botY
  drawWalls = function() {
    var j, len, results, wall;
// YOUR CODE HERE
// Use a for loop to go through each wall
// Draw the top wall (brown) and bottom wall (green)
    results = [];
    for (j = 0, len = walls.length; j < len; j++) {
      wall = walls[j];
      ctx.fillStyle = '#8B4513';
      ctx.fillRect(wall.x, 0, WALL_WIDTH, wall.topH);
      ctx.fillStyle = '#228B22';
      results.push(ctx.fillRect(wall.x, wall.botY, WALL_WIDTH, H - wall.botY));
    }
    return results;
  };

  // ============================================================
  // CHALLENGE 4: Draw the carrots!
  // ============================================================
  // Draw orange rectangles for carrots that haven't been collected

  // You will need to:
  // - Loop through each carrot in the carrots array
  // - Skip carrots where carrot.got is true (already collected)
  // - Draw an orange rectangle at carrot.x, carrot.y

  // HINTS:
  // - Orange color: '#FF8C00'
  // - Carrots are 16 pixels wide and 24 pixels tall
  // - Use "continue if carrot.got" to skip collected carrots
  drawCarrots = function() {};

  // YOUR CODE HERE
  // Loop through carrots and draw ones that haven't been collected

  // ============================================================
  // DRAWING HELPERS (don't change these)
  // ============================================================
  drawBackground = function() {
    ctx.fillStyle = '#87CEEB';
    ctx.fillRect(0, 0, W, H);
    ctx.fillStyle = '#4CAF50';
    return ctx.fillRect(0, H - 30, W, 30);
  };

  drawPowerups = function() {
    var j, len, powerup, results;
    results = [];
    for (j = 0, len = powerups.length; j < len; j++) {
      powerup = powerups[j];
      if (powerup.got) {
        continue;
      }
      ctx.fillStyle = powerup.type === 'axe' ? '#4444FF' : '#44FF44';
      ctx.beginPath();
      ctx.arc(powerup.x + 15, powerup.y + 15, 15, 0, Math.PI * 2);
      ctx.fill();
      ctx.fillStyle = 'white';
      ctx.font = 'bold 14px Arial';
      ctx.textAlign = 'center';
      results.push(ctx.fillText((powerup.type === 'axe' ? 'A' : 'W'), powerup.x + 15, powerup.y + 20));
    }
    return results;
  };

  drawScore = function() {
    ctx.fillStyle = 'white';
    ctx.font = 'bold 20px Arial';
    ctx.textAlign = 'left';
    return ctx.fillText('Score: ' + score, 10, 28);
  };

  drawPowerupIndicators = function() {
    var yPos;
    if (hasAxe) {
      ctx.fillStyle = '#4444FF';
      ctx.fillRect(W / 2 - 30, 40, 60, 20);
      ctx.fillStyle = 'white';
      ctx.font = '12px Arial';
      ctx.textAlign = 'center';
      ctx.fillText('AXE', W / 2, 54);
    }
    if (hasWacker) {
      ctx.fillStyle = '#44FF44';
      yPos = hasAxe ? 65 : 40;
      ctx.fillRect(W / 2 - 40, yPos, 80, 20);
      ctx.fillStyle = 'white';
      ctx.font = '12px Arial';
      ctx.textAlign = 'center';
      return ctx.fillText('WACKER', W / 2, yPos + 14);
    }
  };

  drawBtn = function(id, x, y, w, h, text, color = '#4444AA') {
    btns[id] = {x, y, w, h};
    ctx.fillStyle = color;
    ctx.fillRect(x, y, w, h);
    ctx.fillStyle = 'white';
    ctx.font = 'bold 18px Arial';
    ctx.textAlign = 'center';
    return ctx.fillText(text, x + w / 2, y + h / 2 + 6);
  };

  // ============================================================
  // SCREENS (don't change these)
  // ============================================================
  drawHome = function() {
    drawBackground();
    ctx.fillStyle = 'white';
    ctx.font = 'bold 36px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('Bouncy Bunny', W / 2, 80);
    drawBunny(W / 2, 150);
    ctx.fillStyle = '#333';
    ctx.font = '16px Arial';
    ctx.fillText(SKINS[currentSkin].name, W / 2, 190);
    ctx.fillText('Best: ' + bestScore, W / 2, 230);
    ctx.fillText('Coins: ' + coins, W / 2, 255);
    drawBtn('play', W / 2 - 80, 280, 160, 50, 'PLAY', '#4CAF50');
    return drawBtn('shop', W / 2 - 80, 350, 160, 45, 'SHOP', '#FF9800');
  };

  drawGame = function() {
    drawBackground();
    drawWalls();
    drawCarrots();
    drawPowerups();
    drawBunny(BUNNY_X, bunnyY);
    drawScore();
    drawPowerupIndicators();
    if (waiting) {
      ctx.fillStyle = 'rgba(0,0,0,0.4)';
      ctx.fillRect(0, 0, W, H);
      ctx.fillStyle = 'white';
      ctx.font = 'bold 28px Arial';
      ctx.textAlign = 'center';
      return ctx.fillText('Tap or SPACE to start!', W / 2, H / 2);
    }
  };

  drawOver = function() {
    drawBackground();
    drawWalls();
    ctx.fillStyle = 'rgba(0,0,0,0.6)';
    ctx.fillRect(0, 0, W, H);
    ctx.fillStyle = '#FF5555';
    ctx.font = 'bold 40px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('Game Over!', W / 2, 120);
    ctx.fillStyle = '#FFD700';
    ctx.font = 'bold 28px Arial';
    ctx.fillText('Score: ' + score, W / 2, 170);
    ctx.font = '18px Arial';
    ctx.fillText('Best: ' + bestScore, W / 2, 200);
    drawBtn('again', W / 2 - 80, 240, 160, 50, 'Play Again', '#4CAF50');
    return drawBtn('home', W / 2 - 80, 310, 160, 45, 'Home', '#666666');
  };

  drawShop = function() {
    var btnColor, cardY, i, j, ref;
    drawBackground();
    ctx.fillStyle = 'rgba(255,255,255,0.9)';
    ctx.fillRect(20, 20, W - 40, H - 40);
    ctx.fillStyle = '#333';
    ctx.font = 'bold 24px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('Skin Shop', W / 2, 55);
    ctx.font = '16px Arial';
    ctx.fillText('Coins: ' + coins, W / 2, 80);
    for (i = j = 0, ref = SKINS.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
      cardY = 100 + i * 75;
      ctx.fillStyle = i === currentSkin ? '#E0FFE0' : '#F0F0F0';
      ctx.fillRect(40, cardY, W - 80, 65);
      ctx.fillStyle = SKINS[i].color;
      ctx.beginPath();
      ctx.arc(80, cardY + 32, 18, 0, Math.PI * 2);
      ctx.fill();
      ctx.strokeStyle = '#333';
      ctx.lineWidth = 2;
      ctx.stroke();
      ctx.fillStyle = '#333';
      ctx.font = '16px Arial';
      ctx.textAlign = 'left';
      ctx.fillText(SKINS[i].name, 110, cardY + 28);
      ctx.font = '12px Arial';
      ctx.fillText((owned[i] ? 'Owned' : SKIN_COST[i] + ' coins'), 110, cardY + 46);
      if (i === currentSkin) {
        drawBtn('skin' + i, W - 130, cardY + 18, 70, 30, 'Wearing', '#4CAF50');
      } else if (owned[i]) {
        drawBtn('skin' + i, W - 130, cardY + 18, 70, 30, 'Wear', '#2196F3');
      } else {
        btnColor = coins >= SKIN_COST[i] ? '#FF9800' : '#999';
        drawBtn('skin' + i, W - 130, cardY + 18, 70, 30, 'Buy', btnColor);
      }
    }
    return drawBtn('back', W / 2 - 60, H - 70, 120, 40, 'Back', '#666');
  };

  // ============================================================
  // CHALLENGE 5: Bunny physics!
  // ============================================================
  // Make the bunny fall with gravity and jump when flapping

  // How gravity works:
  // - bunnySpeed starts at 0
  // - Each frame, we ADD gravity to bunnySpeed (makes it fall faster)
  // - Then we ADD bunnySpeed to bunnyY (moves the bunny down)

  // How flapping works:
  // - Set bunnySpeed to a NEGATIVE number (negative = up!)
  applyGravity = function() {
    // YOUR CODE HERE
    // Add GRAVITY to bunnySpeed to make the bunny accelerate downward
    return bunnySpeed += GRAVITY;
  };

  moveBunny = function() {
    // YOUR CODE HERE
    // Add bunnySpeed to bunnyY to move the bunny
    return bunnyY += bunnySpeed;
  };

  flap = function() {
    // YOUR CODE HERE
    // Set waiting to false (game has started)
    // Set bunnySpeed to negative FLAP_POWER to go up
    waiting = false;
    return bunnySpeed = -FLAP_POWER;
  };

  // ============================================================
  // CHALLENGE 6: Keep bunny on screen!
  // ==========================================================
  // Stop the bunny at the ceiling, end game at the ground
  checkCeiling = function() {};

  // YOUR CODE HERE
  // If bunnyY is less than BUNNY_SIZE:
  //   - Set bunnyY to BUNNY_SIZE (keep on screen)
  //   - Set bunnySpeed to 0 (stop moving)
  checkGround = function() {};

  // YOUR CODE HERE
  // If bunnyY is greater than (H - 30 - BUNNY_SIZE):
  //   - Call gameOver()

  // ============================================================
  // CHALLENGE 7: Move everything left!
  // ============================================================
  // Move walls, carrots and powerups toward the bunny
  // Give points when bunny flies past a wall
  moveWalls = function() {};

  // YOUR CODE HERE
  // Use a for loop to go through each wall:
  //   - Subtract WALL_SPEED from wall.x to move it left
  //   - If wall hasn't been scored yet AND bunny passed it:
  //     - Set wall.scored to true
  //     - Add 1 to score

  // HINT: Bunny passes a wall when wall.x + WALL_WIDTH < BUNNY_X
  moveCarrots = function() {};

  // YOUR CODE HERE
  // Use a for loop to move each carrot left by WALL_SPEED
  movePowerups = function() {};

  // YOUR CODE HERE
  // Use a for loop to move each powerup left by WALL_SPEED
  removeOldStuff = function() {
    // Remove walls, carrots, and powerups that went off the left side
    walls = walls.filter(function(w) {
      return w.x + WALL_WIDTH > 0;
    });
    carrots = carrots.filter(function(c) {
      return c.x + 20 > 0;
    });
    return powerups = powerups.filter(function(p) {
      return p.x + 30 > 0;
    });
  };

  // ============================================================
  // COLLISION HELPER (don't change this)
  // ============================================================

  // This checks if two rectangles are overlapping (touching)
  // Returns true if they overlap, false if they don't
  boxesOverlap = function(x1, y1, w1, h1, x2, y2, w2, h2) {
    return x1 < x2 + w2 && x1 + w1 > x2 && y1 < y2 + h2 && y1 + h1 > y2;
  };

  // ============================================================
  // CHALLENGE 8: Check if bunny hits walls!
  // ============================================================
  // Use boxesOverlap to detect collisions with walls
  // If bunny has a powerup, destroy the wall instead of dying

  // The bunny's hitbox is a square:
  //   - Left edge: BUNNY_X - BUNNY_SIZE
  //   - Top edge: bunnyY - BUNNY_SIZE
  //   - Width and Height: BUNNY_SIZE * 2

  // The top wall's hitbox:
  //   - Position: wall.x, 0
  //   - Size: WALL_WIDTH, wall.topH

  // The bottom wall's hitbox:
  //   - Position: wall.x, wall.botY
  //   - Size: WALL_WIDTH, H - wall.botY
  checkWallCollision = function() {
    var bunnyBoxSize, bunnyLeft, bunnyTop;
    // Calculate bunny's hitbox
    bunnyLeft = BUNNY_X - BUNNY_SIZE;
    bunnyTop = bunnyY - BUNNY_SIZE;
    return bunnyBoxSize = BUNNY_SIZE * 2;
  };

  // YOUR CODE HERE
  // For each wall:
  //   - Check if bunny overlaps with top wall using boxesOverlap
  //   - If hit: use axe to destroy wall (set wall.topH = 0) or gameOver
  //   - Check if bunny overlaps with bottom wall
  //   - If hit: use wacker to destroy wall (set wall.botY = H) or gameOver

  // Remember to set hasAxe or hasWacker to false after using them!
  // Use "return" after gameOver() to stop checking more walls

  // ============================================================
  // CHALLENGE 9: Collect carrots!
  // ============================================================
  // Check if bunny touches a carrot and collect it

  // Carrot hitbox: carrot.x, carrot.y, width 16, height 24
  checkCarrotCollision = function() {
    var bunnyBoxSize, bunnyLeft, bunnyTop;
    bunnyLeft = BUNNY_X - BUNNY_SIZE;
    bunnyTop = bunnyY - BUNNY_SIZE;
    return bunnyBoxSize = BUNNY_SIZE * 2;
  };

  // YOUR CODE HERE
  // For each carrot:
  //   - Skip if carrot.got is true (already collected)
  //   - Check if bunny overlaps with carrot using boxesOverlap
  //   - If touching: set carrot.got to true, add points and coins

  // ============================================================
  // CHALLENGE 10: Collect powerups!
  // ============================================================
  // Check if bunny touches a powerup and give it to them

  // Powerup hitbox: powerup.x, powerup.y, width 30, height 30
  // If powerup.type is 'axe', set hasAxe to true
  // Otherwise set hasWacker to true
  checkPowerupCollision = function() {
    var bunnyBoxSize, bunnyLeft, bunnyTop;
    bunnyLeft = BUNNY_X - BUNNY_SIZE;
    bunnyTop = bunnyY - BUNNY_SIZE;
    return bunnyBoxSize = BUNNY_SIZE * 2;
  };

  // YOUR CODE HERE
  // For each powerup:
  //   - Skip if powerup.got is true
  //   - Check if bunny overlaps with powerup
  //   - If touching: set powerup.got to true, give the right powerup

  // ============================================================
  // SPAWNING (don't change this section)
  // ============================================================
  spawnWall = function() {
    var botY, carrotY, topH, type;
    topH = 50 + Math.random() * (H - GAP_SIZE - 110);
    botY = topH + GAP_SIZE;
    walls.push({
      x: W,
      topH: topH,
      botY: botY,
      scored: false
    });
    if (Math.random() < 0.6) {
      carrotY = topH + 20 + Math.random() * (GAP_SIZE - 60);
      carrots.push({
        x: W + WALL_WIDTH / 2 - 8,
        y: carrotY,
        got: false
      });
    }
    if (walls.length % POWERUP_EVERY === 0) {
      type = Math.random() < 0.5 ? 'axe' : 'wacker';
      return powerups.push({
        x: W + WALL_WIDTH + 20,
        y: topH + GAP_SIZE / 2 - 15,
        type: type,
        got: false
      });
    }
  };

  // ============================================================
  // GAME STATE (don't change this section)
  // ============================================================
  resetGame = function() {
    score = 0;
    frames = 0;
    bunnyY = H / 2;
    bunnySpeed = 0;
    walls = [];
    carrots = [];
    powerups = [];
    hasAxe = false;
    hasWacker = false;
    return waiting = true;
  };

  gameOver = function() {
    if (score > bestScore) {
      bestScore = score;
    }
    saveData();
    return screen = 'OVER';
  };

  // ============================================================
  // INPUT (don't change this section)
  // ============================================================
  hitBtn = function(id, x, y) {
    var b;
    b = btns[id];
    if (!b) {
      return false;
    }
    return x >= b.x && x <= b.x + b.w && y >= b.y && y <= b.y + b.h;
  };

  handleClick = function(x, y) {
    var i, j, ref, results;
    switch (screen) {
      case 'HOME':
        if (hitBtn('play', x, y)) {
          resetGame();
          return screen = 'GAME';
        } else if (hitBtn('shop', x, y)) {
          return screen = 'SHOP';
        }
        break;
      case 'GAME':
        return flap();
      case 'OVER':
        if (hitBtn('again', x, y)) {
          resetGame();
          return screen = 'GAME';
        } else if (hitBtn('home', x, y)) {
          return screen = 'HOME';
        }
        break;
      case 'SHOP':
        if (hitBtn('back', x, y)) {
          return screen = 'HOME';
        } else {
          results = [];
          for (i = j = 0, ref = SKINS.length; (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
            if (hitBtn('skin' + i, x, y)) {
              if (owned[i]) {
                currentSkin = i;
                results.push(saveData());
              } else if (coins >= SKIN_COST[i]) {
                coins -= SKIN_COST[i];
                owned[i] = true;
                currentSkin = i;
                results.push(saveData());
              } else {
                results.push(void 0);
              }
            } else {
              results.push(void 0);
            }
          }
          return results;
        }
    }
  };

  onClick = function(e) {
    var r, x, y;
    r = canvas.getBoundingClientRect();
    x = (e.clientX - r.left) * (W / r.width);
    y = (e.clientY - r.top) * (H / r.height);
    return handleClick(x, y);
  };

  onTouch = function(e) {
    var r, t, x, y;
    e.preventDefault();
    t = e.touches[0];
    r = canvas.getBoundingClientRect();
    x = (t.clientX - r.left) * (W / r.width);
    y = (t.clientY - r.top) * (H / r.height);
    return handleClick(x, y);
  };

  onKey = function(e) {
    if (e.key === ' ') {
      e.preventDefault();
      if (screen === 'HOME') {
        resetGame();
        return screen = 'GAME';
      } else if (screen === 'GAME') {
        return flap();
      }
    }
  };

  // ============================================================
  // MAIN GAME LOOP (don't change this section)
  // ============================================================
  update = function() {
    if (screen !== 'GAME' || waiting) {
      return;
    }
    frames = frames + 1;
    // Physics
    applyGravity();
    moveBunny();
    checkCeiling();
    checkGround();
    // Movement
    moveWalls();
    moveCarrots();
    movePowerups();
    removeOldStuff();
    // Spawn new walls
    if (frames % SPAWN_TIME === 0) {
      spawnWall();
    }
    // Collisions
    checkWallCollision();
    checkCarrotCollision();
    return checkPowerupCollision();
  };

  draw = function() {
    btns = {};
    switch (screen) {
      case 'HOME':
        return drawHome();
      case 'GAME':
        return drawGame();
      case 'OVER':
        return drawOver();
      case 'SHOP':
        return drawShop();
    }
  };

  gameLoop = function() {
    update();
    draw();
    return requestAnimationFrame(gameLoop);
  };

  // ============================================================
  // START THE GAME!
  // ============================================================
  setup();

}).call(this);
